name: ArgoCD Deploy Action
description: Cria uma aplicação no ArgoCD caso ela não exista

inputs:
  nome-aplicacao: 
    description: Nome da aplicação que vai fazer deploy
    required: true


runs:
  using: node20
  main: dist/index.js