name: Build and tag as latest

on:
  push:
    branches:
      - main

jobs:
  build-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # necessário para tags

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build with ncc
        run: npx ncc build src/index.js -o dist

      - name: Commit dist (se mudou)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "build: update dist with ncc" || echo "No changes"

      - name: Tag as latest and push
        run: |
          git tag -f latest
          git push origin latest --force